server:
    port: 3000

db:
    type: "postgres"
    port: 5432
    database: "StudentMgmtDb"
    host: "localhost"
    username: "postgres"
    password: "admin"
    synchronize: false
    dropSchema: false

notifications:
    enabled: false

mailing:
    enabled: false
    smtp:
        host: "smtp.server"
        useSecureConnection: false
        username: "username"
        password: "password"
        port: 587

authentication:
    url: "http://147.172.178.30:8080"

logger:
    levels:
        - error
        - warn
        - debug
        - verbose
    requests: false
    dbErrors: false
