server:
    basePath: "http://localhost:3000"
    port: 3000

db:
    type: "postgres"
    port: 5432
    database: "StudentMgmtDb"
    host: "localhost"
    username: "postgres"
    password: "admin"
    synchronize: false
    dropSchema: false

notifications:
    enabled: false

mailing:
    enabled: false

authentication:
    url: "http://147.172.178.30:8080"

logger:
    levels:
        - error
        - warn
        - debug
        - verbose
    requests: false
    dbErrors: false
