server:
    port: 9999

db:
    synchronize: true
    dropSchema: true

mailing:
    enabled: false
    from: "no-reply@student-mgmt-system"
    clientBasePath: "http://localhost:4200"
    smtp:
        host: "smtp.server"
        useSecureConnection: false
        username: "username"
        password: "password"
        port: 587

logger:
    levels:
        - error
        - warn
        - debug
    requests: false
    dbErrors: true
